apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | default "school-erp" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: school-erp
